
[functions.create-crisis-alert]
enabled = true
verify_jwt = true
import_map = "./functions/create-crisis-alert/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-crisis-alert/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-crisis-alert/*.html" ]

[functions.claim-crisis-alert]
enabled = true
verify_jwt = true
import_map = "./functions/claim-crisis-alert/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/claim-crisis-alert/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/claim-crisis-alert/*.html" ]

[functions.cancel-crisis-alert]
enabled = true
verify_jwt = true
import_map = "./functions/cancel-crisis-alert/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/cancel-crisis-alert/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/cancel-crisis-alert/*.html" ]

[functions.alert-manager]
enabled = true
verify_jwt = true
import_map = "./functions/alert-manager/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/alert-manager/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/alert-manager/*.html" ]

[functions.admin-manager]
enabled = true
verify_jwt = true
import_map = "./functions/admin-manager/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-manager/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-manager/*.html" ]
